'use strict';

const messages = require('./messages.json');

const USER_ID_HEADER = 'x-remote-user';

const TOKEN_OPERATION_CREATE = 'create';
const TOKEN_OPERATION_REVOKE = 'revoke';

const TOKEN_STATUS_REVOKED = 'revoked';
const TOKEN_STATUS_VALID   = 'valid';
const TOKEN_DURATION       = 7;
const TOKEN_DURATION_UNIT  = 'days';

const COLLECTION_TOKENS = 'tokens';
const COLLECTION_USERS  = 'users';

module.exports = {
  UNEXPECTED_NUM_DOCS: messages.ERRORS.UNEXPECTED_NUM_DOCS,
  USER_NOT_TOKEN_OWNER: messages.ERRORS.USER_NOT_TOKEN_OWNER,
  WEB_TOKEN_CREATION_MSG: messages.WEB_TOKEN.CREATION_MSG,
  WEB_TOKEN_REVOCATION_MSG: messages.WEB_TOKEN.REVOCATION_MSG,
  USER_ID_HEADER,
  TOKEN_OPERATION_CREATE,
  TOKEN_OPERATION_REVOKE,
  TOKEN_STATUS_REVOKED,
  TOKEN_STATUS_VALID,
  TOKEN_DURATION,
  TOKEN_DURATION_UNIT,
  COLLECTION_TOKENS,
  COLLECTION_USERS,
};
